### ISSUE TITLE
"for of" loop ES6 not recognized as valid syntax

### ISSUE THREAD

**Issue by boyko11** [davidB/yuicompressor-maven-plugin#89]
Using plugin version 1.5.1.
The "**for-of**" loop ES6 syntax is not considered valid and fails the build:

**`                    for(var enrlmnt of studentSectionsEnrolledInThisMeeting) {
                        console.log(enrlmnt);
                    }`**

build	03-Mar-2016 10:36:23	[ERROR] /opt/app/bamboo/bamboo-home/xml-data/build-dir/LMS-MYP-JOB1/src/main/webapp/scripts/bigblue.js [197:39]: missing ; after for-loop initializer
build	03-Mar-2016 10:36:23	[ERROR] ...bigblue.js:line 197:**column 39:missing ; after for-loop initializer**
build	03-Mar-2016 10:36:23		                    **for(var enrlmnt of studentSectionsEnrolledInThisMeeting) {**

**Comment by davidB** [comment]
yuicompressor 2.4.7/2.4.8 doesn't support ES 6 (it was released in 2014).

**Comment by boyko11** [comment]
Thanks! Your plugin has been great for our project!
