### ISSUE TITLE
let variable and es6 function script ES6 not recognized as valid syntax

### ISSUE THREAD

**Issue by naveenkumar096** [davidB/yuicompressor-maven-plugin#95]
ex: - 1 x.forEach( (value, key, set) => {
});

above syntax not recognized

**Comment by chrisjshields** [comment]
Is this plugin still being used? ES6 was finalized in June 2015.

**Comment by naveenkumar096** [comment]
Present not using

**Comment by davidB** [comment]
this maven plugin is to allow using yuicompressor within a maven project. Support for some javascript version should be provided by [yuicompressor](https://yui.github.io/yuicompressor/) itself, and should be available on a maven repository.
